--COMANDO PARA VER LA ESTRUCTURA DE LA RELACION
sp_columns Personas;
---AGREGAR UNA COLUMNA A UNA TABLA EXISTENTE
ALTER TABLE Personas ADD Email varchar(25);
---ELIMINAR UNA COLUMNA DE UNA TABLA EXISTENTE
ALTER TABLE Personas DROP COLUMN Email;
---MODIFICAR COLUMNA (En este caso nombre y tipo de datos)
ALTER TABLE Personas ALTER COLUMN PersonaID TINYINT; 
