---------SELECCIONA REGISTROS CON UN RANGO DE VALORES ESPECIFICADAS----------------
---SELECT BETWEEN
SELECT * FROM PersonaInsert
WHERE Age BETWEEN 18 AND 25;
---SELECT NOT BETWEEN
SELECT * FROM PersonaInsert
WHERE Age NOT BETWEEN 18 AND 25;